Web.AfrinextInvest.com/Controllers/PartSocialesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;
using Web.AfrinextInvest.com.Models;

namespace Web.AfrinextInvest.com.Controllers
{
    public class PartSocialesController : Controller
    {
        private readonly AfrinextInvestContext _context;

        public PartSocialesController(AfrinextInvestContext context)
        {
            _context = context;    
        }

        // GET: PartSociales
        public async Task<IActionResult> Index()
        {
            return View(await _context.PartSociale.ToListAsync());
        }

        // GET: PartSociales/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var partSociale = await _context.PartSociale
                .SingleOrDefaultAsync(m => m.Id == id);
            if (partSociale == null)
            {
                return NotFound();
            }

            return View(partSociale);
        }

        // GET: PartSociales/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: PartSociales/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,NomActivite,DescriptionActivite,AgeActivite,ChiffreAffaire,NbPartsACeder,PrixUnitaire,SecteurActivite,Pays,ActiviteVerifiee")] PartSociale partSociale)
        {
            if (ModelState.IsValid)
            {
                _context.Add(partSociale);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(partSociale);
        }

        // GET: PartSociales/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var partSociale = await _context.PartSociale.SingleOrDefaultAsync(m => m.Id == id);
            if (partSociale == null)
            {
                return NotFound();
            }
            return View(partSociale);
        }

        // POST: PartSociales/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,NomActivite,DescriptionActivite,AgeActivite,ChiffreAffaire,NbPartsACeder,PrixUnitaire,SecteurActivite,Pays,ActiviteVerifiee")] PartSociale partSociale)
        {
            if (id != partSociale.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(partSociale);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PartSocialeExists(partSociale.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(partSociale);
        }

        // GET: PartSociales/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var partSociale = await _context.PartSociale
                .SingleOrDefaultAsync(m => m.Id == id);
            if (partSociale == null)
            {
                return NotFound();
            }

            return View(partSociale);
        }

        // POST: PartSociales/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var partSociale = await _context.PartSociale.SingleOrDefaultAsync(m => m.Id == id);
            _context.PartSociale.Remove(partSociale);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool PartSocialeExists(int id)
        {
            return _context.PartSociale.Any(e => e.Id == id);
        }
    }
}

Web.AfrinextInvest.com/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web.AfrinextInvest.com</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Menu</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Afrinext Invest</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Projets" asp-action="Index">Projets</a></li>
                    <li><a asp-area="" asp-controller="PartSociales" asp-action="Index">Parts Sociales</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>

                <ul class="nav navbar-nav navbar-right">

                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a asp-area="" asp-controller="Admin" asp-action="Index">Administration</a></li>

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">@User.Identity.Name <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Profil</a></li>
                                <li role="separator" class="divider"></li>
                                <li>
                                    <form asp-action="LogOff" asp-controller="Account" method="post">
                                        <input class="btn btn-link navbar-link" type="submit" value="Déconnexion" />
                                    </form>
                            </ul>
                        </li>
                    }
                    else
                    {
                        <li><a asp-area="" asp-controller="Account" asp-action="Login">Connexion</a></li>
                        <li><a asp-area="" asp-controller="Account" asp-action="Register">Inscription</a></li>
                    }
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - Web.AfrinextInvest.com</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script>
            $(document).ready(function () {
                $('[data-toggle="tooltip"]').tooltip();
            });
        </script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>