Web.AfrinextInvest.com/Controllers/MyController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System.Threading.Tasks;
using Web.AfrinextInvest.com.Data;
using Web.AfrinextInvest.com.Identity;
using Web.AfrinextInvest.com.Models;

namespace Web.AfrinextInvest.com.Controllers
{
    [Authorize]
    public class MyController : Controller
    {
        private readonly AfrinextInvestContext _context;
        private readonly IdentityContext _identitycontext;
        private readonly string _userId;
        private readonly UserManager<User> _usermanager;

        public MyController(AfrinextInvestContext context, IdentityContext identitycontext, UserManager<User> usermanager, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            _identitycontext = identitycontext;
            _usermanager = usermanager;
            _userId = httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
        }

        public async Task<IActionResult> Index()
        {
            var loggedInUser = await _usermanager.FindByIdAsync(this._userId);
            string Name = loggedInUser.Prenom + " " + loggedInUser.Nom;
            ViewData.Add("Nom", Name);
            return View();
        }

        public async Task<IActionResult> Profile()
        {
            var loggedInUser = await _usermanager.FindByIdAsync(this._userId);
            string Name = loggedInUser.Prenom + " " + loggedInUser.Nom;
            ViewData.Add("Nom", Name);
            return View(loggedInUser);
        }

        [Route("My/Profile/Edit")]
        [HttpGet]
        public async Task<IActionResult> EditProfile()
        {
            var loggedInUser = await _usermanager.FindByIdAsync(this._userId);
            string Name = loggedInUser.Prenom + " " + loggedInUser.Nom;
            ViewData.Add("Nom", Name);
            return View(loggedInUser);
        }

        [HttpPost]
        public async Task<IActionResult> EditProfile([Bind("Prenom","Nom","UserName","Email","Bio")] User user)
        {
            var loggedInUser = await _usermanager.FindByIdAsync(this._userId);
            string Name = loggedInUser.Prenom + " " + loggedInUser.Nom;
            ViewData.Add("Nom", Name);

            if (ModelState.IsValid)
            {
                _context.Update(user);
                await _context.SaveChangesAsync();
            }
            return View(loggedInUser);
        }
    }
}

Web.AfrinextInvest.com/Views/Admin/ProjectDetails.cshtml
@model Web.AfrinextInvest.com.Models.Projet
@using System.Globalization;

@{
    ViewData["Title"] = "Details";
    // Gets a NumberFormatInfo associated with the en-US culture.
    NumberFormatInfo nfi = new CultureInfo("fr-SN").NumberFormat;
    Layout = "_SubLayout";
}

<section class="col-md-10 col-sm-9">
    <h2>Détails du projet</h2>
    <hr />
    <article class="col-md-8">
        <div class="panel panel-default">
            <div class="panel-heading" style="height:400px;"></div>
            <div class="panel-body">
                <small><a href="#" class="btn btn-link"><i class="glyphicon glyphicon-flash"></i> @Model.SecteurActvite </a></small>
                <small> <a class="btn btn-link"><i class="glyphicon glyphicon-map-marker"></i> @Model.Pays </a> </small>
                @if (Model.State.Equals("Validé"))
                {
                    <span class="pull-right label label-success"><i class="glyphicon glyphicon-ok-sign"></i> Vérifié</span>
                }
                else
                {
                    if (Model.State.Equals("En Attente"))
                    {
                        <span class="pull-right label label-warning"><i class="glyphicon glyphicon-refresh"></i> En attente</span>
                    }
                    else
                    {
                        <span class="pull-right label label-danger"><i class="glyphicon glyphicon-eye-close"></i> Brouillon</span>
                    }
                }
                <br />
                <p class="text-right text-muted">
                    <i>Soumis le @Model.DateCreation par Mamoudou Aliou Ba </i>
                </p>

                <h4 class="text-center ani-project-title text-info"> @Model.Nom </h4>
                <p> @Model.Description </p>
                <div class="ani-project-report" style="margin-top: 2em; padding-top: 1em; border-top: 3px solid #00ff21;">
                    <div class="col-md-3 text-center" style="padding:0;">
                        <i class="glyphicon glyphicon-user"></i> <br />
                        <small> 14 Contributions</small>
                    </div>
                    <div class="col-md-6 text-center" style="padding:0;">
                        <i class="glyphicon glyphicon-usd"></i> <br />
                        <small> 15624889 CFA / 14789556 Collectés</small>
                    </div>
                    <div class="col-md-3 text-center" style="padding:0;">
                        <i class="glyphicon glyphicon-usd"></i> <br />
                        <small> 156458 CFA Restant</small>
                    </div>
                </div>
            </div>
        </div>
    </article>
    <div class="col-md-4">
        <a asp-action="ProjectIndex" class="btn btn-link">Retour</a>
        @if (Model.State.Equals("Brouillon"))
        {
            <button class="disabled btn btn-xs btn-success">Approuver</button>
        }
        else
        {
            if (Model.State.Equals("En attente"))
            { 
                <a asp-action="ProjectValidate" asp-route-Id="@Model.Id" class="btn btn-xs btn-success">Approuver</a>
            }
        }
        <a asp-action="ProjectHold" asp-route-Id="@Model.Id" class="btn btn-xs btn-danger">Suspendre</a>
    </div>
</section>

Web.AfrinextInvest.com/Views/Admin/ProjectIndex.cshtml
@model IEnumerable<Web.AfrinextInvest.com.Models.Projet>

@{ 
    Layout = "_SubLayout";
}

<section class="col-md-10 col-sm-9">
    <h2>Liste des projets soumis</h2>
    <hr />

    <table class="table table-responsive table-striped">
        <thead>
            <tr>
                <th>N°</th>
                <th>Nom</th>
                <th>Budget requis</th>
                <th>Secteur d'activité</th>
                <th>Pays d'activité</th>
                <th>Statut</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.Nom</td>
                    <td>@item.BudgetRequis</td>
                    <td>@item.SecteurActvite.nomSecteur</td>
                    <td>@item.Pays</td>
                    <td>
                        @if(@item.isVerified && !@item.isDraft)
	                    {
		                        <span class="text-success">Vérifié</span>
                        }
                        else {
                            @if (!@item.isVerified && !@item.isDraft)
                            {
                                <span class="text-warning">En attente</span>
                            }
                            else
                            {
                                <span class="text-danger">Brouillon</span>
                            }
                        }
                    </td>
                    <td>
                        <a asp-action="ProjectDetails" asp-route-Id="@item.Id" class="btn btn-link">Détails</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</section>

Web.AfrinextInvest.com/Views/Admin/RoleCreate.cshtml
@model Web.AfrinextInvest.com.Identity.Role
@{
    ViewData["Title"] = "Nouveau Role";
    Layout = "_SubLayout";
}

<section class="col-md-10">
    <h2>Nouveau rôle d'utilisateur</h2>
    <hr />
    <div class="col-md-12" style="margin:0.5em auto;">
    </div>
        
    <div class="col-md-6">
        <form asp-action="RoleCreate" method="post">
            <div class="form-group">
                <label asp-for="Name">Nom</label>
                <input class="form-control" asp-for="Name" />
            </div>
            <div class="form-group">
                <label asp-for="Description">Description</label>
                <textarea class="form-control" asp-for="Description"></textarea>
            </div>
            <div class="form-group">
                <input type="submit" value="Enregistrer" class="btn btn-success" />
                <a asp-action="RolesIndex" class="btn btn-danger">Annuler</a>
            </div>
        </form>
    </div>

</section>

Web.AfrinextInvest.com/Views/Admin/RolesIndex.cshtml
@model IEnumerable<Web.AfrinextInvest.com.Identity.Role>

@{
    ViewData["Title"] = "Liste des Roles";
    Layout = "_SubLayout";
}

<section class="col-md-10">
    <h2>Roles utilisateurs</h2>
    <hr />
    <div class="col-md-12" style="margin:0.5em auto;">
        <a asp-action="RoleCreate" class="btn btn-xs btn-primary">Ajouter</a>
    </div>
    <table class="table table-striped table-hover">
        <tr class="">
            <th>Nom</th>
            <th>Description</th>
            <th>Action</th>
        </tr>
        @foreach (var Item in Model)
        {
            <tr>
                <td>@Item.Name</td>
                <td>@Item.Description</td>
                <td>
                    <a href="" class="btn btn-xs btn-success">Details</a>
                    <a href="" class="btn btn-xs btn-danger">Modifier</a>
                </td>
            </tr>
        }
    </table>
</section>

Web.AfrinextInvest.com/Views/Admin/UserCreate.cshtml
@model Web.AfrinextInvest.com.Identity.RegisterViewModel
@{
    ViewData["Title"] = "Nouvel utilisateur";
    Layout = "_SubLayout";
}

<section class="col-md-10">
    <h2>Nouvel utilisateur</h2>
    <hr />
    <div class="col-md-12" style="margin:0.5em auto;">
    </div>

    <div class="col-md-6">
        <form asp-action="UserCreate" method="post">
            <div class="form-group">
                <label asp-for="Prenom"></label>
                <input asp-for="Prenom" class="form-control" />
                <span class="text-danger" asp-validation-for="Prenom"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nom"></label>
                <input asp-for="Nom" class="form-control" />
                <span class="text-danger" asp-validation-for="Nom"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserName" ></label>
                <input asp-for="UserName" class="form-control" />
                <span class="text-danger" asp-validation-for="UserName"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email"></label>
                <input asp-for="Email" class="form-control" />
                <span class="text-danger" asp-validation-for="Email"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password"></label>
                <input asp-for="Password" class="form-control" />
                <span class="text-danger" asp-validation-for="Password"></span>
            </div>
            <div class="form-group">
                <label asp-for="ConfirmPassword"></label>
                <input asp-for="ConfirmPassword" class="form-control" />
                <span class="text-danger" asp-validation-for="ConfirmPassword"></span>
            </div>
            <div class="form-group">
                <label asp-for="Portable"></label>
                <input asp-for="Portable" class="form-control" />
                <span class="text-danger" asp-validation-for="Portable"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateNaissance"></label>
                <input asp-for="DateNaissance" class="form-control" />
                <span class="text-danger" asp-validation-for="DateNaissance"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Enregistrer" class="btn btn-sm btn-success" />
                <a asp-action="UsersIndex" class="btn btn-sm btn-danger">Annuler</a>
            </div>
        </form>
    </div>

</section>

Web.AfrinextInvest.com/Views/Admin/UserDetails.cshtml
@model Web.AfrinextInvest.com.Identity.User
@{
    ViewData["Title"] = "Informations d'utilisateur";
    Layout = "_SubLayout";
    var groupes = Model.Claims.ToList();
    var roles = Model.Roles.ToList();
}

<section class="col-md-10">
    <h2>Informations de l'utilisateur</h2>
    <hr />
    <div class="table-responsive col-md-6">
        <table class="table table-striped" style="border:1px solid gainsboro;">
            <tr>
                <td>Pseudo</td>
                <td>@Model.UserName</td>
            </tr>
            <tr>
                <td>Nom</td>
                <td> @Model.Prenom @Model.Nom </td>
            </tr>
            <tr>
                <td>Adresse E-mail</td>
                <td> @Model.Email</td>
            </tr>
            <tr>
                <td>Téléphone</td>
                <td>@Model.Portable</td>
            </tr>
                
            <tr>
                <td>Anniversaire</td>
                <td>@Model.DateNaissance</td>
            </tr>
            <tr>
                <td>A Propos</td>
                <td></td>
            </tr>
            <tr>
                <td>Groupes</td>
                <td>
                    @foreach (var item in groupes)
                    { @item.ClaimValue ; }
                </td>
            </tr>
            <tr>
                <td>Roles</td>
                <td>
                    @foreach (var role in roles)
                    { @role.RoleId ; }
                </td>
            </tr>
        </table>
    </div>
    <div class="col-md-6">
        <a asp-action="UsersIndex" class="btn btn-link">Retour</a>
        <a class="btn btn-xs btn-warning">Réinitialiser le mot de passe</a>
        <a class="btn btn-xs btn-danger">Suspendre le compte</a>
    </div>

</section>

Web.AfrinextInvest.com/Views/Admin/UsersIndex.cshtml
@model IEnumerable<Web.AfrinextInvest.com.Identity.User>

@{
ViewData["Title"] = "UsersIndex";
Layout = "_SubLayout";
}

<section class="col-md-10">
    <h2>Utilisateurs</h2>
    <hr />
    <div class="col-md-12" style="margin:0.5em auto;">
        <a asp-action="UserCreate" class="btn btn-xs btn-primary">Ajouter</a>
    </div>
    <table class="table table-striped table-hover">
        <tr>
            <th>Nom</th>
            <th>Pseudo</th>
            <th>E-Mail</th>
            <th>Telephone</th>
            <th>Statut</th>
            <th>Action</th>
        </tr>
        @foreach(var Item in Model){
            <tr>
                <td>@Item.Prenom @Item.Nom</td>
                <td>@Item.UserName</td>
                <td>@Item.Email</td>
                <td>@Item.Portable</td>
                <td></td>
                <td>
                    <a asp-action="UserDetails" asp-route-UserName ="@Item.UserName" class="btn btn-link">Details</a>
                </td>
            </tr>
}
    </table>
</section>

Web.AfrinextInvest.com/Views/Admin/_PartialHeader.cshtml
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Menu</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Afrinext Invest</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">

                @if (User.Identity.IsAuthenticated)
                    {
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">@User.Identity.Name <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a asp-controller="My" asp-action="Index">Profil</a></li>
                            <li role="separator" class="divider"></li>
                            <li>
                                <form asp-action="LogOff" asp-controller="Account" method="post">
                                    <input class="btn btn-link navbar-link" type="submit" value="Deconnexion" />
                                </form>
                        </ul>
                    </li>
                    }
                    else
                    {
                    <li><a asp-area="" asp-controller="Account" asp-action="Login">Connexion</a></li>
                    <li><a asp-area="" asp-controller="Account" asp-action="Register">Inscription</a></li>
                    }
            </ul>
        </div>
    </div>
</nav>

Web.AfrinextInvest.com/Views/Admin/_PartialSidebar.cshtml
<nav class="col-md-2">
    <ul class="nav nav-pills nav-stacked">
        <li><a asp-controller="Admin" asp-action="ProjectIndex">Projets </a></li>
        <li><a asp-controller="Admin" asp-action="UsersIndex">Utilisateurs </a></li>
        <li><a asp-controller="Admin" asp-action="RolesIndex">Roles </a></li>
        <li><a asp-controller="Admin" asp-action="ClaimsIndex">Groupes </a></li>
    </ul>
</nav>

Web.AfrinextInvest.com/Views/Admin/_SubLayout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web.AfrinextInvest.com</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    @Html.Partial("_PartialHeader")    
    <div class="container-fluid body-content" style="margin-top:1em;">
        <div class="row">
            @Html.Partial("_PartialSidebar")
            @RenderBody()
        </div>
        <hr />
        <footer>
            <p>&copy; 2017 - Web.AfrinextInvest.com</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script>
            $(document).ready(function () {
                $('[data-toggle="tooltip"]').tooltip();
            });
        </script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>